### ISSUE TITLE
problem with wslib

### ISSUE THREAD

**Issue by buscon** [dathinaios/sc_osx_standalone#11]
hi,

if I include the [wslib library](https://github.com/supercollider-quarks/wslib) I get the following errors:
ERROR: Class extension for nonexistent class 'Document'
     In file:'../../SCClassLibrary/wslib/wslib-classes/Lang/Workflow/extDocument-closeAllHelp.sc'
ERROR: Class extension for nonexistent class 'Document'
     In file:'../../SCClassLibrary/wslib/wslib-classes/Lang/Workflow/extDocument-openStartup.sc'
ERROR: Class extension for nonexistent class 'DOMElement'
     In file:'../../SCClassLibrary/wslib/wslib-classes/Main Features/SVGFile/extVarious-SVGFile.sc'

any Ideas on how I can fix that?

**Comment by dathinaios** [comment]
Did you try to just remove the files that cause the error?

**Comment by buscon** [comment]
hi, 

sorry for the late answer.
I removed those files and now that problem is solved.

I run into [another problem](https://github.com/dathinaios/sc_osx_standalone/issues/12) though
