### ISSUE TITLE
Problem with SC plugins

### ISSUE THREAD

**Issue by buscon** [dathinaios/sc_osx_standalone#12]
hi,

I added the SC plugins to the SCClassLibrary folder:
cp -r /Users/myUser/Library/Application Support/SuperCollider/Extensions/SC3plugins SCClassLibrary/SCPlugins

then I get the following warning (even if use the name "plugins" for the plugins directory):
i	Compiling directory 'SCClassLibrary'
WARNING: Could not open directory: 'plugins'

and the following error:
exception in GraphDef_Recv: UGen 'ArrayMax' not installed.
*** ERROR: SynthDef temp__0 not found
FAILURE IN SERVER /s_new SynthDef not found
even though ArrayMax is part of the SCPlugins (and it works in the installed SC 3.12.2).

do you manage to use the SC plugins?

**Comment by dathinaios** [comment]
Hey, sorry fore the late reply. I was on holiday 🙂

Did you get it to work? If not try to only copy the plugin folder you need and do so inside `SCClassLibrary` in the root folder. The `plugin` warning should be unrelated to your issues (I will push a fix for that separately).

Let me know how it goes if you try it.

**Comment by dathinaios** [comment]
Will close this now. Do try the current version and let me know if you are still having trouble.
