### ISSUE TITLE
update to use sclang -a

### ISSUE THREAD

**Issue by miguel-negrao** [dathinaios/sc_osx_standalone#4]
Should use the standalone mode of sclang. See https://github.com/miguel-negrao/scStandalone

**Comment by dathinaios** [comment]
Hello Miguel :)

I assume this is for 3.7 right?
I prefer to wait until the new version is out of the alpha/beta stage. This repository is working fine for OSX as it is (at least in my tests).

Is there any documentation for the -a flag? Does it just mean that it will ignore all the hard coded directories and use the yaml file?

**Comment by miguel-negrao** [comment]
Hey ! :-)

Yes, for 3.7, so yeah, since you have to copy the binaries, makes sense to wait for 3.7.0.

As you read on the list, there is no documentation yet, it just excludes all hardcoded paths.

Do you need to do any linking magic with the binaries or you just copy the libraries to the same relative paths ? 

In any case this should be documented for those that want to make their own standalones from their own binaries, and there is no point in documenting for 3.6 I guess, since 3.7 is coming out very soon.

**Comment by dathinaios** [comment]
Regarding the `-a` flag in `sclang` maybe I am missing something but I perceive it as wrong design to have hardcoded paths in sclang and **then** have a flag to exclude them. Specific arguments should always be supplied and not hardcoded...

In any case, it is what it is. At least now there is a way.

I will leave this open and implement it when `3.7` is out. As far as I'm aware is just copying to the paths but I will fiddle with it when the time comes.

Thanks!

**Comment by miguel-negrao** [comment]
> Regarding the -a flag in sclang maybe I am missing something but I perceive it as wrong design to have hardcoded paths in sclang and then have a flag to exclude them. Specific arguments should always be supplied and not hardcoded...

There are default locations for configuration files which are "hardcoded" in the sense that they are standard across desktop environments. Configuration files are supposed to be in certain folders, so it was chosen to put the class library there (at least in linux). In linux this is specified by 
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html. The paths are hardcoded mostly for historical reasons, they were already hardcoded before the language configuration was introduced, but also I guess it is a trade-off between customizability and stability. If the defaults paths were not hardcoded, then they would have to be in a configuration file which would ship with sc. if that configuration file (yaml) was corrupted or deleted the user couldn't even boot a functioning sclang since no class library would be found. I guess that could be accounted for by having an option to generate a clean yaml file from the ide with the default locations, but this could possibly generate more confusion than the benefits.  I guess the "Extensions" folder could be deprecated in time, now that we have the language configuration. As for the class library I think that would need more discussion.

> As far as I'm aware is just copying to the paths but I will fiddle with it when the time comes.

Ok, in that case instructions on how to create a standalone for both osx and linux can be added to the wiki, or documentation, for 3.7.

**Comment by dathinaios** [comment]
Thanks for the info. Indeed you are right. The application support is a standard folder in `OSX`. The awkword part is the class library being in:
`/Applications/SuperCollider.app/Contents/Resources/SCClassLibrary`

> Ok, in that case instructions on how to create a standalone for both osx and linux can be added to the wiki, or documentation, for 3.7.

Ah yes that would be nice. In that case I will do a test in the next days and see if it make sense to include it in the form of instructions or as a link to the repository.

**Comment by dathinaios** [comment]
Just an update. I tried to build sc from source to see if I can have a look before SC 3.7 and potentially add the instructions to the help files but I had issues with building it on my machine. 

I will wait until the next BETA and have a look. In any case the instructions should be the same with the updated versions. The only changes will be with the script to use the -a flag.

Is there consensus to update the help file for standalones (which is if I remember correctly for OSX only) with instructions for linux and mac pointing to the script based method? If that is the case I would be happy to do the update.

**Comment by dathinaios** [comment]
I am closing this as it turns out that the main issue is with linking the QT libraries.
