### ISSUE TITLE
3.8 issues resolved?

### ISSUE THREAD

**Issue by dataexcess** [dathinaios/sc_osx_standalone#6]
Hi, is there any news regarding the QT linking issues? Will this ever be fixed and if not what would be a good alternative to this to make a SC Standalone?

Thank you!

**Comment by dathinaios** [comment]
Hi there, this issue has not been resolved as far as I am aware though I haven't checked for ages.. 

Last time I was chatting about it, there didn't seem to be much of an intention to solve it which is quite a shame as this was such a simple solution for creating standalone apps. As of now there are some crazily convoluted instructions [in the SC documentation](https://doc.sccode.org/Guides/standalones.html) but I haven't attempted to follow the guide just yet.

You could make a post in the [SuperCollider Forum](https://scsynth.org/) as an attempt to initiate a conversation about the linking issue. I have already tried a couple of time some years back but, if people show interest, there might be more of an incentive to fix it.

**Comment by dataexcess** [comment]
> Hi there, this issue has not been resolved as far as I am aware though I haven't checked for ages..
> 
> Last time I was chatting about it, there didn't seem to be much of an intention to solve it which is quite a shame as this was such a simple solution for creating standalone apps. As of now there are some crazily convoluted instructions [in the SC documentation](https://doc.sccode.org/Guides/standalones.html) but I haven't attempted to follow the guide just yet.
> 
> You could make a post in the [SuperCollider Forum](https://scsynth.org/) as an attempt to initiate a conversation about the linking issue. I have already tried a couple of time some years back but, if people show interest, there might be more of an incentive to fix it.

Hi dathinaios :)
That's exactly what I did, end then stumbled upon your project...
here's the discussion I started, but I have the feeling there's not that much interest in tghe community:
https://scsynth.org/t/how-to-remove-the-ide-window-in-a-standalone/1397/7

Cheers,
D

**Comment by dathinaios** [comment]
Ok, interesting news 🙂 

I went back to see if the issue was resolved but did not see any progress. Nevertheless, I thought I would give it a try with the new version as I haven't tried this for a few years. Surprisingly after some hacking around I got it working again! Could you do some testing? I haven't merged with the master as I am not sure it is going to be stable but I made a temporary release that you can get [here](https://github.com/dathinaios/sc_osx_standalone/releases/tag/3.10.4).

You also need to download the attached `Frameworks` folder and simply unzip it inside the main folder of the project. GitHub would not allow me to add it to the repo as it contains really large files. Let me know how that goes and if everything works I will merge to master and update the documentation.

Thanks 🙃👍

**Comment by dataexcess** [comment]
> Ok, interesting news 🙂
> 
> I went back to see if the issue was resolved but did not see any progress. Nevertheless, I thought I would give it a try with the new version as I haven't tried this for a few years. Surprisingly after some hacking around I got it working again! Could you do some testing? I haven't merged with the master as I am not sure it is going to be stable but I made a temporary release that you can get [here](https://github.com/dathinaios/sc_osx_standalone/releases/tag/3.10.4).
> 
> You also need to download the attached `Frameworks` folder and simply unzip it inside the main folder of the project. GitHub would not allow me to add it to the repo as it contains really large files. Let me know how that goes and if everything works I will merge to master and update the documentation.
> 
> Thanks 🙃👍

Wooohooow, awsome!
Will start testing asap and let u know.
Thanks 🙏

**Comment by dataexcess** [comment]
For my case it seems to work perfectly 😎
Thank you for the effort and quick and swift reply.
🤝

**Comment by dathinaios** [comment]
No problem at all. Thank you for reminding me to have another go. I am extremely happy this works 😀
