### ISSUE TITLE
Couple the SC bleeding edge build?

### ISSUE THREAD

**Issue by dataexcess** [dathinaios/sc_osx_standalone#7]
Hi there,

Once again, thank you so much for this amazing project, it helps me a lot.
Unfortunately, I discovered that my standalone project relies on some code only present in the bleeding edge build of supercollider (namely the LinkClock.sc class).

I tried to replace the SCClassLibrary by the one from the bleeding edge build, but I guess it"s not as simple as that.

So my question: Is it possible to make the standalone helper to work with a different build/branch of supercollider? Preferably the bleeding edge build. 

Thank you!
🙏

**Comment by dathinaios** [comment]
Hello 🙂

I'm afraid I can't chase the ever changing bleeding edge build but I can give you some advice and answer any questions regarding issues that come up.

If you have the app bundle for the latest version then you need to right click and `show package contents`. In there you should find many folders and files that have the same name as the ones used in the standalone. For example `Frameworks`, `PlugIns`, `sclang` and `scsynth` etc. replace the current files with the new versions and, in theory, everything should work (famous last words).

Let me know of any errors you encounter and I will try to help!

**Comment by dataexcess** [comment]
Hi,

I tried to replace all folders: Frameworks, Plugins and Resources. I also moved sclang from the folder /MacOS into /Resources since that is where it was located in the bleeding edge build.

when I run 'sh run.sh' in terminal I get the following:

```
compiling class library...
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

run.sh: line 9:  3950 Abort trap: 6           ./Resources/sclang -llangconf.yaml init.scd
```

Any idea? Thnx :)

**Comment by dathinaios** [comment]
Aha! This is the error I was getting when the QT library could not be linked. Have you copied across the `PlugIns` folder? Notice this is not the SuperCollider `plugins` folder that should be copied in the `resources` folder! They are easily confused. The `cocoa` QT plugin is to be found in the `PlugIns` folder.

**Comment by dataexcess** [comment]
Yes, I literally replaced the /PlugIns folder with the one from the bleeding edge build. Not the /Resources/plugins one directly (although indirectly yes, because I also replaced the complete /Resources folder..

**Comment by dathinaios** [comment]
Replacing the whole `Resources` folder might be the issue cause various files (like `sclang`) are in different folders in the App bundle. You will need to find the individual files from the different locations in the App bundle. Let me know how it goes.

**Comment by dathinaios** [comment]
I decided to try it out and it is working here. Not sure where you went wrong 🙂

Download it from [here](https://www.dropbox.com/s/h8olqms19f2g6y2/sc_osx_standalone_3.11.zip?dl=0)

**Comment by dataexcess** [comment]
> I thought I'll try it out and it is working here. Not sure where you went wrong 🙂
> 
> Download it from [here](https://www.dropbox.com/s/h8olqms19f2g6y2/sc_osx_standalone_3.11.zip?dl=0)
> 
> (I will remove the file as it is in my personal dropbox so make sure you keep a copy in addition to your working one)

Ah yours is working! nice, thnx!
I somehow managed to screw up hehe... 🙃

**Comment by dathinaios** [comment]
no problem 🙃

**Comment by dathinaios** [comment]
@dataexcess Hi there, I am trying to update to 3.11 for Catalina and I am having trouble. Did we by any chance manage to get it working in this thread?

**Comment by dathinaios** [comment]
@dataexcess Do you happen to have the working project folder I've send you above to give it a try?

**Comment by dataexcess** [comment]
Nooo I don't. I got a new laptop and those files are now gone from my old one already.
Sorry!
