### ISSUE TITLE
Microphone permissions

### ISSUE THREAD

**Issue by linke999** [dathinaios/sc_osx_standalone#9]
I'm having troubles getting input from the microphone (or any audio) when running the standalone app-bundle made in Platypus. It does however work perfectly when running the executable from within the bundle - AppName.app/Contents/MacOS/ via Terminal. I tried running a s.meter with the app and it shows no input when running the app (but it does when running the exe). I think this has to do with permissions, but the app doesn't ask to be added to the permissions list when started. Tried codesigning also, doesn't work. I'm on macOS 10.14.6. It works on my friend's computer which is running 10.13.x so I'm guessing it's a problem that was introduced with Mojave, and has to do with the OS not allowing it, but I don't know how to get around it.

**Comment by linke999** [comment]
Also thank you for this great template!

**Comment by dathinaios** [comment]
If you are still interested in this could you give it a try with the current version?

**Comment by dathinaios** [comment]
Will close this now. Do try the current version and let me know if you are still having trouble.
